stages :
  - test
  - clean_apache_root
  - deploy_new

lint-check :
  stage : test
  script : 
    find -regex ".*\.\(php\)" | while read file; do php -l "$file"; done


remove_last_repo :
  stage : clean_apache_root
  script :
    - rm -f /var/www/html/bankpro -r
  only:
    - dev
    - master
    - feature/ci-cd

deploy_code :
  stage : deploy_new
  script :
    - cd ../../../../../../
    - cd /var/www/html
    - pwd
  only:
    - dev
    - master
    - feature/ci-cd
